import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components';
import fml1 from '../assets/fml1.jpeg';
import fml2 from '../assets/fml2.jpeg';
import fml3 from '../assets/fml3.jpeg';


const Container = styled.div`
  display: flex;
  flex-direction: row;
  overflow: hidden;
  overflow-x: scroll;
  width: 50rem;
  border-radius: 1rem;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Image src={fml1} alt="family" width={800} height={600} />
        <Image src={fml2} alt="family" width={600} height={600} />
        <Image src={fml3} alt="family" width={600} height={600} />
      </Container>
    </>
  )
}
